[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "3xKPBz9pgfcvDZJz4dyoFzVeG1MWms1QwyqSuuxMDTZs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec jest --preset ts-jest"
